PRIME-1723 small admin changes
bcgov/moh-prime pull request #1427
Opened 2021-07-09 18:26 UTC by hogmann

2021-07-09 23:46 UTC, mtpultz submitted a review, later dismissed

2021-07-10 00:30 UTC, johnnyl6 requested changes
Tried up/down arrow on the Notes page in PR environment, note remains unchanging after switching enrollee.

![image](https://user-images.githubusercontent.com/58282608/125146573-509f2a00-e0db-11eb-9ef0-93180e019e5d.png)

2021-07-14 23:44 UTC, hogmann commented
> Tried up/down arrow on the Notes page in PR environment, note remains unchanging after switching enrollee.
> 
Alright fixed that with the note pages, as well with the upload pages.

2021-07-15 00:03 UTC, johnnyl6 submitted a review, later dismissed
LGTM 🚀

2021-07-17 20:35 UTC, mtpultz commented on prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudicator-notes/adjudicator-notes.component.ts
> +        this.route.params.subscribe(params => this.getAdjudicatorNotes(params.id));
Should quickly cast these `+`

2021-07-17 20:35 UTC, mtpultz commented on prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudicator-notes/adjudicator-notes.component.ts
> +        this.route.params.subscribe(params => this.getSiteRegistrationNotes(params.id));
Should quickly cast these `+`

2021-07-20 00:40 UTC, hogmann commented on prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-adjudicator-documents/enrollee-adjudicator-documents.component.ts
>    public onSaveDocuments(documentGuids: string[]) {
I will add a post it note to try and get engrained in my head, as well as the +

2021-07-21 00:41 UTC, AnaisHebert approved these changes
![coffee_parrot](https://user-images.githubusercontent.com/53796823/126412601-f102ea53-cced-48bb-b4bd-d7c9c19dbce2.gif)

2021-07-21 18:40 UTC, johnnyl6 approved these changes

2021-07-21 21:02 UTC, merged