Feature/prime 1770 swapping signing auth
bcgov/moh-prime pull request #1621
Opened 2021-09-16 00:27 UTC by hogmann

Need to go through tests and check still. but here some things

2021-09-17 21:07 UTC, Paahn requested changes

2021-09-17 21:07 UTC, Paahn commented on prime-angular-frontend/src/app/core/resources/organization-resource.service.ts
> +     * pending a tranfer
spelling check

2021-09-17 21:07 UTC, Paahn commented on prime-dotnet-webapi/Controllers/OrganizationsController.cs
> +            var careSettingCodes = await _organizationService.GetCareSettingCodesForPendingTranferAsync(organizationId, organization.SigningAuthorityId);
missing "s" in Transfer, probably should be GetCareSettingCodesForPendingTransferAsync

2021-09-17 21:07 UTC, Paahn commented on prime-dotnet-webapi/Controllers/OrganizationsController.cs
> +        /// Clear Pending Tranfer Flag on an organization.
transfer

2021-09-17 21:07 UTC, Paahn commented on prime-dotnet-webapi/Controllers/OrganizationsController.cs
> +            await _organizationService.FinalizeTranferAsync(organizationId);
FinalizeTransferAsync

2021-09-17 21:07 UTC, Paahn commented on prime-dotnet-webapi/Services/OrganizationService.cs
> +        public async Task<IEnumerable<CareSettingType>> GetCareSettingCodesForPendingTranferAsync(int organizationId, int signingAuthorityId)
missing "s" in Transfer, probably should be GetCareSettingCodesForPendingTransferAsync

2021-09-17 21:07 UTC, Paahn commented on prime-dotnet-webapi/Services/OrganizationService.cs
> +        public async Task FinalizeTranferAsync(int organizationId)
FinalizeTransferAsync

2021-09-17 21:07 UTC, Paahn commented on prime-dotnet-webapi/Services/interfaces/IOrganizationService.cs
> +        Task<IEnumerable<CareSettingType>> GetCareSettingCodesForPendingTranferAsync(int organizationId, int signingAuthorityId);
same missing "s" in Transfer

2021-09-17 21:07 UTC, Paahn commented on prime-dotnet-webapi/Services/interfaces/IOrganizationService.cs
> +        Task FinalizeTranferAsync(int organizationId);
same as above

2021-09-20 16:45 UTC, AMiKaH reviewed
Other than the typos Panos mentioned, looks good.

2021-09-20 23:30 UTC, Paahn approved these changes
LGTM

2021-09-22 16:00 UTC, johnnyl6 approved these changes
LGTM

2021-09-22 16:00 UTC, johnnyl6 commented on prime-angular-frontend/src/app/modules/site-registration/pages/electronic-organization-agreement-page/electronic-organization-agreement-page.component.ts
> +import { AbstractEnrolmentPage } from '@lib/classes/abstract-enrolment-page.class';
unused import

2021-09-22 20:50 UTC, hogmann commented on prime-angular-frontend/src/app/modules/site-registration/pages/electronic-organization-agreement-page/electronic-organization-agreement-page.component.ts
> +import { AbstractEnrolmentPage } from '@lib/classes/abstract-enrolment-page.class';
removed :)

2021-09-22 21:29 UTC, merged