PRIME-1927 Update Email Status doesnt priority non-statuses
bcgov/moh-prime pull request #1895
Opened 2021-12-21 22:36 UTC by johnnyl6

- Update emailLogs of non-pending status first
- Update pending emailLogs only If no other non-completed status emailLogs updated

2021-12-22 18:14 UTC, james-hollinger commented on prime-dotnet-webapi/Services/EmailService.cs
> +                .Where(e => e.LatestStatus != ChesStatus.Pending)
so this will never update email logs that are pending?

2021-12-22 19:47 UTC, james-hollinger requested changes
There was a discussion about this ticket when it was first intook a sprint or two ago and it looks like those details weren’t passed on and they weren’t outlined in the ticket appropriately. We should have a quick talk about it since at the time we assumed someone else was going to make these updates with the knowledge of those discussions.

2021-12-23 09:38 UTC, james-hollinger commented on prime-dotnet-webapi/Models/Email/EmailLog.cs
> +        public int? UpdateCount { get; set; }
`UpdateCount` should be an `int`, which will initialize at 0

2021-12-23 09:39 UTC, james-hollinger commented on prime-dotnet-webapi/Services/EmailService.cs
>                  .OrderBy(e => e.UpdatedTimeStamp)
you need to use `.ThenBy(e => e.UpdatedTimeStamp)` here

2021-12-23 09:41 UTC, james-hollinger commented on prime-dotnet-webapi/Services/EmailService.cs
> +                email.UpdateCount = email.UpdateCount.HasValue ? email.UpdateCount.Value + 1 : 1;
with `UpdateCount` being an `int`, this can just be `email.UpdateCount++`

2021-12-31 22:21 UTC, AMiKaH approved these changes

2022-01-04 20:16 UTC, james-hollinger approved these changes
LGTM

2022-01-05 17:48 UTC, merged