PRIME-2254 HA Static Text Changes
bcgov/moh-prime pull request #2179
Opened 2022-07-27 16:58 UTC by bergomi02

HA Static Text Changes

2022-08-05 19:12 UTC, Paahn requested changes

2022-08-11 21:20 UTC, bergomi02 commented on prime-angular-frontend/src/app/shared/components/auth/site-reg-access/site-reg-access.component.html
> +            A person authorized by the health authority can registers the sites.
good catch.

2022-08-25 16:14 UTC, Paahn commented on prime-angular-frontend/src/app/shared/components/auth/site-reg-access/site-reg-access.component.html
> +            A person authorized by the health authority can registers the sites.
text change?

2022-08-25 16:32 UTC, Paahn approved these changes
LGTM

2022-08-25 16:34 UTC, bergomi02 commented on prime-angular-frontend/src/app/shared/components/auth/site-reg-access/site-reg-access.component.html
> +            A person authorized by the health authority can registers the sites.
my bad, the change was not pushed.

2022-08-30 23:41 UTC, merged