PRIME-1187 Business Licence page updates
bcgov/moh-prime pull request #966
Opened 2020-11-20 00:17 UTC by johnnyl6

Updated label texts on the Business Licence page

2020-11-20 01:02 UTC, neophyte57 approved these changes
Looks good to me  :-)

2020-11-20 01:27 UTC, hogmann commented
I left a comment on the ticket asking Jolie about the wording the ticket was asking for since ”(as it appears on you business licence)" is duplicated in the summary right below. I would touch base tomorrow morning before merging in.

2020-11-20 01:28 UTC, hogmann requested changes

2020-11-20 01:28 UTC, hogmann commented on prime-angular-frontend/src/app/modules/site-registration/pages/business-licence/business-licence.component.html
> +        <ng-container appPageSubheader2Title>Site Name (as it appears on your business licence)</ng-container>
We may want to adjust wording since duplicated explanation to the summary below.

2020-11-24 00:11 UTC, mtpultz approved these changes
👍

2020-11-25 19:26 UTC, AnaisHebert approved these changes
⭐️

2020-11-25 19:53 UTC, merged